ENCRYPTION_FILE = "encryption_key.key"
ENCRYPTION_KEY = ""
ENCRYPTION_SET = True
OPENAI_API_KEY = ""
OPENAI_ENGINE = "gpt-4-1106-preview"
SLACK_API_TOKEN = ""
SLACK_BOT_TOKEN = ""
VERIFICATION_TOKEN = ""